### This notebook is my remider of informations gained during the course on Coursera.

#### In theory

1. Vector: 
    -> operations: + (two vectors), * (by scalar);
    -> properities: associative => (a+b)+c = a+(b+c);
    -> vector lenght: |a| = √(a^2+b^2);
    -> dot product (multiplication two vectors): a.b = ai * bi + aj * bj:
        - commutative: a.b = b.a,
        - distributive over addition: a.(b+c) = a.b + a + c,
        - associative over scalar multiplication: a.(Lb) = L(a.b),
        - in orthogonal case: if cos90(degree) = 0(rad) => cos0 = 1 => a.b = |a| * |b|,
        - vector projection: a * a.b / |a| * |a|,
        - scalar projection: a.b / |r|;
        
2. Basis:
    -> set on n vectors:
        - this vector span the space,
        - each vectors are linear independence;
        
3. Matrix:
    -> operations on matrix: 
        - add one row to second row,
        - swap places of two rows,
        - multiplication some row by scalar;
    -> operation between two matrix:
        - addiction,
        - substraction;
        - multiplication (use Einstein summation convention -> abik = sum(aij * bjk), AB = C => cik = aij * bjk);
     -> transform type:
        - shears,
        - invert,
        - mirror,
        - rotation,
        - transpose (Aij.T = Aji),
        - stretch;
      -> type of matrix:
        - zero,
        - orthogonal,
        - row,
        - column,
        - diagonal,
        - unit;
      -> property:
        - determinant,
        - A.T * A = I if |A| = +- 1,
        - A.T = A^(-1)
      * to solve systems of equations we could use Gaussian elimination.

#### In Python

In [6]:
# Vectors intro
vector_1 = [1, 2, 3, 4, 5]

vector_1[0] # 1

vector_1[-1] # 5

len(vector_1) # 5

vector_1[0] + vector_1[1] # 3

vector_1[0]*2 # 2

vector_1.append(6)

for x in vector_1:
    print(x) # 1 2 3 4 5 6
    pass
    
vector_1.remove(2)

for x in vector_1:
    print(x) # 1 3 4 5 6
    pass
    
vector_2 = [5,4,3,2,1]

vector_1[3] + vector_2[0] # 10

vector_1 + vector_2 # [1,3,4,5,6,5,4,3,2,1]

In [2]:
# short intro to numpy

# of course,import
import numpy as np

a = np.array([1,2,3]) # array([1, 2, 3]), creale array
np.zeros((2,2)) # array([[ 0.,  0.],
                       #[ 0.,  0.]]), array with zeros 
    
a = np.array([[1,2],[2,3]])
b = np.array([[4,5],[6,7]])

a + b  # [[ 5  7]
       # [ 8 10]]
sum(a) # 8
a - b  # [[-3 -3]
       # [-4 -4]]
a * b  # [[ 4 10]
       # [12 21]]
a / b  # [[ 0.25 0.4]
       # [ 0.33333333 0.42857143]]
a**2   # [[1 4]
       # [4 9]]
pass

In [3]:
# Matrix intro_1
matrix_1 = np.array([[1,2,3,4,5],
                    [1,2,3,4,5],
                    [1,2,3,4,5],
                    [1,2,3,4,5],
                    [1,2,3,4,5]])
matrix_1.shape # (5,5)
# alternative 
A = np.arange(9).reshape(3,3) # [[0 1 2]
                                #[3 4 5]
                                #[6 7 8]]
matrix_1[1] # [1,2,3,4,5]
matrix_1[1][2] # 3
matrix_1[3:] # [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
matrix_1 = np.append(matrix_1,[5,4,3,2,1]) # add row
matrix_1 # [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 5, 4, 3, 2, 1]
matrix_1 = np.delete(matrix_1,[5])
matrix_1 # [1, 2, 3, 4, 5, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 5, 4, 3, 2, 1]
matrix_1 = np.insert(matrix_1,6, [1,2,3,4,8]) # add column
matrix_1 # [1, 2, 3, 4, 5, 2, 1, 2, 3, 4, 8, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 5, 4, 3, 2, 1]
pass

In [4]:
# use same helpful numpy's function -> at first - IMPORTS :) 
from numpy.linalg import norm, inv

a = np.array([[1, 2], [3, 4]])

inv(a) # array([[-2. ,  1. ],
               #[ 1.5, -0.5]])
    
np.transpose(matrix_1) # array([1, 2, 3, 4, 5, 2, 1, 2, 3, 4, 8, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3,
                               # 4, 5, 1, 2, 3, 4, 5, 5, 4, 3, 2, 1])
matrix_1.T # the same as above 

matrix_1 @ matrix_1 # 423
np.dot(matrix_1, matrix_1) # the same dot product as above

A = np.eye(3) # create identity matrix
np.linalg.det(A) # determinant
eigenvalues, eigenvectors = np.linalg.eig(A) # calculate eingenvalue ([ 1.  1.  1.]) and eigenvectors ( [[ 1.  0.  0.]
                                                                                                    # [ 0.  1.  0.]
                                                                                                    # [ 0.  0.  1.]])